engines/admin/config/routes.rb
Admin::Engine.routes.draw do

  root 'projects#index'

  resources :sessions, only: [:new, :create] do 
    collection do 
      delete 'logout'
    end
  end

  get  'edit_profile', to: 'profile#edit'
  post 'edit_profile', to: 'profile#update'
  
  resources :users
  resources :billings

  resources :projects do 
    resources :pages 
    resources :navs
    resources :subscribe_custom_participations
    resources :subscribes do 
      resources :subscribe_observations
      get 'update_paid'
    end

    
    resources :popups
    resources :informs
    resources :bills
    resources :participations do 
      collection do 
        get 'show_candidates'
      end
    end

    resources :documents
    resources :winners
    
    resources :consults do 
      get 'next_situation'
    end

    resources :resources
  end

end

engines/admin/app/controllers/admin/profile_controller.rb
module Admin
  class ProfileController < ApplicationController
    
    def edit
      @user = current_user
    end

    def update

      if params[:user][:password].blank? && params[:user][:password_confirmation].blank?
        params[:user].delete :password
        params[:user].delete :password_confirmation
      end
      
      @user = current_user
      if @user.update(set_params)
        flash[:success] =  t :success
        redirect_to action: :edit
      else
        flash[:danger]  = t :danger
        render action: :edit
      end
    end

    private

    def set_params
      params.require(:user).permit(:name, :email, :password, :privilege, :password_confirmation, :status)
    end
    
  end
end

engines/admin/app/views/admin/profile/_form.html.haml
= simple_form_for @user, url: edit_profile_path, method: :post do |f|
  %h4.ui.dividing.header Formulário
  .three.fields
    = f.input :name, input_html: { placeholder: "Informe o título do concurso"}
    = f.input :email, input_html: { placeholder: "Faça uma breve descrição do concurso"}
  .three.fields
    = f.input :password, hint: (f.object.new_record?)  ? nil : 'deixe em branco caso não queira atualizar a senha', input_html: { placeholder: "Informe o título do concurso"}

    = f.input :password_confirmation, input_html: { placeholder: "Informe o título do concurso"}
  %h4.ui.dividing.header
  .field
    = f.button :submit, class: 'ui button green'

engines/admin/app/views/admin/profile/edit.html.haml
.row
  .column
    %h1.ui.header 
      Editar Perfil
      .sub.header
        Formulário de edição de perfil. 
    .ui.hidden.divider
.ui.hidden.divider
.row
  .column 
    .ui.blue.segment
      = render 'form'