engines/admin/config/routes.rb
Admin::Engine.routes.draw do

  root 'projects#index'

  resources :sessions, only: [:new, :create] do 
    collection do 
      delete 'logout'
    end
  end

  get  'edit_profile', to: 'profile#edit'
  post 'edit_profile', to: 'profile#update'
  
  resources :users
  resources :billings

  resources :projects do 
    resources :pages 
    resources :navs
    resources :subscribe_custom_participations
    resources :subscribes do 
      resources :subscribe_observations
      get 'update_paid'
    end

    
    resources :popups
    resources :informs
    resources :bills
    resources :participations do 
      collection do 
        get 'show_candidates'
      end
    end

    resources :documents
    resources :winners
    
    resources :consults do 
      get 'next_situation'
    end

    resources :resources
  end

end

engines/admin/app/controllers/admin/consults_controller.rb
require_dependency 'admin/application_controller'

module Admin
  class ConsultsController < ApplicationController 
    before_action :set_project
    before_action :set_consults
    
    layout 'sub_application'

    def index
    end

    def show
      @consult  = @project.consults.find(params[:id])
    end

    def next_situation
      @consult = @project.consults.find(params[:consult_id])

      case @consult.situation
      when 'não_lida'
        @consult.update(situation: 1)
      when 'lida'
        @consult.update(situation: 2)
      end
    end

    private

    def set_project
      @project = ::Project.friendly.find(params[:project_id])
    end

    def set_consults
      @consults = @project.consults
    end

  end
end

engines/admin/app/views/admin/consults/_index.html.haml
- @consults.each do |nav|
  %tr 
    %td.collapsing= nav.id
    %td= nav.created_at.strftime('%d/%m/%Y às %H:%M')
    %td.collapsing= nav.situation.humanize
    %td.collapsing
      = link_to "Visualizar", project_consult_path(project_id: @project, id:nav), remote: true, class: 'ui button primary'
      - if nav.não_lida?
        = link_to "Marcar como lida", project_consult_next_situation_path(project_id: @project, consult_id: nav), remote: true, class: 'ui button green'
      - if nav.lida?
        = link_to "Marcar como respondida",  project_consult_next_situation_path(project_id: @project, consult_id: nav), remote: true, class: 'ui button yellow'

engines/admin/app/views/admin/consults/_show.html.haml
%i.close.icon
.header
  Consulta Nº  #{@consult.id}
.image.content
  .ui.grid
    .row
      .column
        %h3
          %p= @consult.created_at.strftime("%d/%m/%Y às %H:%M")
    .row
      .sixteen.wide.column
        = @consult.content.html_safe

engines/admin/app/views/admin/consults/index.html.haml
.row
  .column
    %h1.ui.header 
      Consultas

.ui.hidden.divider
.row
  .column
    %table.ui.celled.table.striped
      %thead
        %tr
          %th Cod.
          %th Data de envio
          %th Situação
          %th
      %tbody.consults-index 
        = render 'index'

engines/admin/app/views/admin/consults/next_situation.js.haml
- if !@consult.errors.any?
  $(".consults-index").html("#{escape_javascript(render 'index')}")

engines/admin/app/views/admin/consults/show.js.haml
$(".ui.modal").html("#{escape_javascript(render 'show')}")
$('.ui.modal').modal('show');