engines/admin/config/routes.rb
Admin::Engine.routes.draw do

  root 'projects#index'

  resources :sessions, only: [:new, :create] do 
    collection do 
      delete 'logout'
    end
  end

  get  'edit_profile', to: 'profile#edit'
  post 'edit_profile', to: 'profile#update'
  
  resources :users
  resources :billings

  resources :projects do 
    resources :pages 
    resources :navs
    resources :subscribe_custom_participations
    resources :subscribes do 
      resources :subscribe_observations
      get 'update_paid'
    end

    
    resources :popups
    resources :informs
    resources :bills
    resources :participations do 
      collection do 
        get 'show_candidates'
      end
    end

    resources :documents
    resources :winners
    
    resources :consults do 
      get 'next_situation'
    end

    resources :resources
  end

end

engines/admin/app/controllers/admin/popups_controller.rb
require_dependency 'admin/application_controller'

module Admin
  class PopupsController < ApplicationController 
    before_action :set_project
    before_action :set_popup, only: [:edit, :update, :destroy]
    
    layout 'sub_application'

    def index
      @popups = @project.popups
    end

    def new
      @popup = @project.popups.new
    end

    def create
      @popup = @project.popups.new(set_params)
      
      if @popup.save 
        flash[:success] =  t :success
        redirect_to action: :index
      else 
        render action: :new
      end
    end

    def edit
    end

    def update
      if @popup.update(set_params)
        flash[:success] =  t :success
        redirect_to action: :index
      else
        render action: :edit
      end
    end

    def destroy
      @popup.destroy
      flash[:success] =  t :success
      redirect_to action: :index
    end

    private

    def set_params
      params.require(:popup).permit(:title, :content, :link, :publish)
    end

    def set_project
      @project = ::Project.friendly.find(params[:project_id])
    end

    def set_popup
      @popup = @project.popups.find(params[:id])
    end

  end
end

engines/admin/app/views/admin/popups/_form.html.haml
= simple_form_for [@project, @popup] do |f|
  .fields
    .field.sixteen.wide
      = f.input :title, label: "Título", placeholder: "Digite o título do Pop-up"
  .fields
    .field.sixteen.wide
      = f.input :link, label: "Link da página", placeholder: "Digite o link onde deverá abrir o Pop-up"
  .fields
    .field.sixteen.wide
      = f.input :content, label: "Conteúdo do pop-up"
  .fields
    .field.four.wide
      = f.input :publish, as: :select, label: "Publicado?"
  %br/
  %br/
  .fields
    .field.twelve.wide
      = f.submit "Salvar Pop-up", class: 'ui button green'
      = link_to "Cancelar",  project_popups_path(@project), class: 'ui button icon'

engines/admin/app/views/admin/popups/edit.html.haml
.row
  .column
    %h1.ui.header 
      Editar Pop-up
    = link_to "Retornar para listagem", project_popups_path(@project)
.ui.hidden.divider
.row
  .column
    = render 'form'

engines/admin/app/views/admin/popups/index.html.haml
.row
  .column
    %h1.ui.header 
      Pop-ups
    = link_to "+ Adicionar Novo Pop-up", new_project_popup_path(@project)

.ui.hidden.divider
.row
  .column
    %table.ui.celled.table.striped
      %thead
        %tr
          %th Nº
          %th Título
          %th Página
          %th Publicado?
          %th
      %tbody
        - @popups.each do |popup|
          %tr 
            %td.collapsing= popup.id
            %td= popup.title
            %td= popup.link
            %td.collapsing= popup.publish ? "Sim" : "Não"
            %td.collapsing
              = link_to "editar", edit_project_popup_path(@project, popup), class: 'ui button blue mini icon'
              = link_to "excluir", project_popup_path(@project, popup), method: :delete, class: 'ui button red mini icon'

engines/admin/app/views/admin/popups/new.html.haml
.row
  .column
    %h1.ui.header 
      Novo Pop-up
    = link_to "Retornar para listagem", project_popups_path(@project)
.ui.hidden.divider
.row
  .column
    = render 'form'