engines/admin/config/routes.rb
Admin::Engine.routes.draw do

  root 'projects#index'

  resources :sessions, only: [:new, :create] do 
    collection do 
      delete 'logout'
    end
  end

  get  'edit_profile', to: 'profile#edit'
  post 'edit_profile', to: 'profile#update'
  
  resources :users
  resources :billings

  resources :projects do 
    resources :pages 
    resources :navs
    resources :subscribe_custom_participations
    resources :subscribes do 
      resources :subscribe_observations
      get 'update_paid'
    end

    
    resources :popups
    resources :informs
    resources :bills
    resources :participations do 
      collection do 
        get 'show_candidates'
      end
    end

    resources :documents
    resources :winners
    
    resources :consults do 
      get 'next_situation'
    end

    resources :resources
  end

end

engines/admin/app/controllers/admin/winners_controller.rb
require_dependency 'admin/application_controller'

module Admin
  class WinnersController < ApplicationController 
    before_action :set_project
    
    layout 'sub_application'

    def index
      @winners = @project.winners
    end

    def new
      @winner  = @project.winners.new
    end

    def show
      @winner = @project.winners.find(params[:id])
    end

    def create
      @winner  = @project.winners.new(set_params)
      
      if @winner.save
        redirect_to [@project, @winner]
      else
        render action: :new
      end
      
    end

    def destroy 
      @winner = @project.winners.find(params[:id])

      @winner.destroy 

      redirect_to action: :index
    end

    private

    def set_project
      @project = ::Project.friendly.find(params[:project_id])
    end

    def set_params
      params.require(:winner).permit(:subscribe_participation_id, :winner_type, :winner_custom_type)
    end

  end
end

engines/admin/app/views/admin/winners/_form.html.haml
= simple_form_for [@project, @winner] do |f|
  .fields  
    .field.wide.three
      = f.input :winner_type, as: :select, label: "Classificação", collection: ::Winner.winner_type_allow(@project).map { |k,v| [k.to_s.humanize, k] }, include_blank: false
    .field.wide.three
      = f.input :subscribe_participation_id, label: "Nº da pasta", as: :string, input_html: { placeholder: "Informe o Nº"}
    .field.wide.three
      = f.submit "Nomear vencedor", class: 'ui button green filter-button', data: { disable_with: t(:disable_with)}

engines/admin/app/views/admin/winners/_show.html.haml
.row
  .column{style: 'text-align:center'}
    %h1= @winner.winner_type.humanize.mb_chars.upcase
    %h1 Pasta Nº #{@winner.subscribe_participation_id} | Inscrição Nº #{@winner.subscribe_participation.subscribe_id}
    
    %h3
      #{@winner.subscribe_participation.subscribe.name.upcase}
    %h4
      #{@winner.subscribe_participation.subscribe.city}/#{@winner.subscribe_participation.subscribe.state.name}
    
    %br/
    %br/
    %h4 Equipe
    %br/
    - if @winner.subscribe_participation.subscribe.subscribe_requireds.present? 
      - @winner.subscribe_participation.subscribe.subscribe_requireds.each do |item|
        = "#{item.name}, "
    - else
      %i Não informou equipe técnica.
    %br/
    %br/
    %h4 Equipe
    %br/
    - if @winner.subscribe_participation.subscribe.subscribe_optionals.present? 
      - @winner.subscribe_participation.subscribe.subscribe_optionals.each do |item|
        = "#{item.name}, "
    - else
      %i Não informou equipe (não obrigatória).
    %br/
    %br/
    %br/
    %br/
    = link_to image_tag('/images/download.png', size: '100x100'), @winner.subscribe_participation.participation_path_url, target: '_blank'
    %br/
    %br/
    %br/
  

engines/admin/app/views/admin/winners/create.js.haml
- if @winner.errors.any?
  $("#form-partial").html("#{escape_javascript(render 'form')}")
- else
  $("#form-partial").fadeOut('slow', function() {
  $("#form-partial").html("#{escape_javascript(render 'show')}") 
  $("#form-partial").fadeIn('slow')
  });

engines/admin/app/views/admin/winners/index.html.haml
.row
  .column
    %h1.ui.header 
      Vencedores
    = link_to "+ Adicionar vencedor", new_project_winner_path(@project)

- if @project.id == 1
  .ui.hidden.divider
  .row
    .column
      %table.ui.celled.table.striped
        %thead
          %tr
            %th Classificação
            %th.collapsing Nº Pasta
            %th.collapsing Nº Inscrição
            %th
        %tbody
          - if @winners.present?
            - @winners.order(:winner_type).each do |winner|
              %tr
                %td= winner.winner_type.mb_chars.humanize.upcase
                %td.collapsing= winner.subscribe_participation_id 
                %td.collapsing= winner.subscribe_participation.subscribe_id if winner.subscribe_participation.present? 
                %td.collapsing
                  = link_to "Visualizar", project_winner_path(@project, winner), target: '_blank', class: 'ui button blue mini' if winner.subscribe_participation.present?
                  = link_to "Remover", project_winner_path(project_id: @project, id: winner), method: :delete, data: { disable_with: t(:disable_with), confirm: "Tem certeza que deseja remover?"}, class: 'ui button red mini'
          - else
            %tr
              %td
                %i Nenhum ganhador registrado.
- else

  .ui.hidden.divider
  .row
    .column
      %table.ui.celled.table.striped
        %thead
          %tr
            %th Classificação
            %th.collapsing Nº Pasta
            %th.collapsing Nº Inscrição
            %th Projeto
            %th Ação
        %tbody
          - if @winners.present?
            - @winners.order(:winner_type).each do |winner|
              %tr
                %td= winner.winner_type.mb_chars.humanize.upcase
                %td.collapsing= winner.subscribe_participation_id 
                %td.collapsing= winner.subscribe_custom_participation.subscribe_id if winner.subscribe_custom_participation.present? 
                %td.collapsing
                  = link_to "#1", winner.subscribe_custom_participation.archive_file_one_url, target: '_blank' if winner.subscribe_custom_participation.archive_file_one?
                  = link_to "#2", winner.subscribe_custom_participation.archive_file_two_url, target: '_blank' if winner.subscribe_custom_participation.archive_file_two?
                %td.collapsing
                  = link_to "Remover", project_winner_path(project_id: @project, id: winner), method: :delete, data: { disable_with: t(:disable_with), confirm: "Tem certeza que deseja remover?"}, class: 'ui button red mini'
          - else
            %tr
              %td
                %i Nenhum ganhador registrado.

engines/admin/app/views/admin/winners/new.html.haml
.row
  .column
    %h2 Nomear vencedor
    = link_to "Voltar a listagem de vencedores", project_winners_path(@project)
.ui.divider.hidden
.row
  .column
    #form-partial
      = render 'form'

engines/admin/app/views/admin/winners/show.html.haml
.row
  .column
    %h2 Nomear vencedor
    = link_to "Voltar a listagem de vencedores", project_winners_path(@project)
.ui.divider.hidden
.row
  .column{style: 'text-align:center'}
    %h1= @winner.winner_type.humanize.mb_chars.upcase
    %h1 Pasta Nº #{@winner.subscribe_participation_id} | Inscrição Nº #{@winner.subscribe_custom_participation.subscribe_id}
    %h3
      #{@winner.subscribe_custom_participation.subscribe.name.upcase}
    %h4
      #{@winner.subscribe_custom_participation.subscribe.city}/#{@winner.subscribe_custom_participation.subscribe.state.name}
    
    %br/
    %br/
    %h4 Equipe
    %br/
    - if @winner.subscribe_custom_participation.subscribe_custom_teams.present? 
      - @winner.subscribe_custom_participation.subscribe_custom_teams.each do |item|
        = "#{item.name.to_s.humanize}, "
    - else
      %i Não informou equipe (não obrigatória).
    %br/
    %br/
    %br/
    %br/
    = link_to image_tag('/images/download.png', size: '100x100'), @winner.subscribe_custom_participation.archive_file_one_url, target: '_blank'
    %br/
    Arquivo 1
    %br/
    %br/
    = link_to image_tag('/images/download.png', size: '100x100'), @winner.subscribe_custom_participation.archive_file_two_url, target: '_blank'
    %br/
    Arquivo 2